# Generated by Django 3.0.3 on 2020-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='Введите адрес ссылки', null=True, verbose_name='Ссылка'),
        ),
    ]
